### ISSUE TITLE
SIGPIPE signal happen

### ISSUE THREAD

**Issue by jarwin123** [artpaul/clickhouse-cpp#3]
when i use invalid clickhouse server ipaddress,the program will hang up，and then  the program have SIGPIPE singnal。
`<the stack is：
```(gdb) c
Continuing.

Program received signal SIGPIPE, Broken pipe.
0x00007ffff790c93d in send () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007ffff790c93d in send () from /lib64/libpthread.so.0
#1  0x00007ffff7b92c2e in clickhouse::SocketOutput::DoWrite (this=0x7fffffffe158, data=0x6161a0, len=41) at /home/idc/clickhouse-cpp/clickhouse/base/socket.cpp:155
#2  0x00007ffff7b9140d in clickhouse::OutputStream::Write (this=0x7fffffffe158, data=0x6161a0, len=41) at /home/idc/clickhouse-cpp/clickhouse/base/output.h:19
#3  0x00007ffff7b923b1 in clickhouse::BufferedOutput::DoFlush (this=0x7fffffffe168) at /home/idc/clickhouse-cpp/clickhouse/base/output.cpp:55
#4  0x00007ffff7b913d7 in clickhouse::OutputStream::Flush (this=0x7fffffffe168) at /home/idc/clickhouse-cpp/clickhouse/base/output.h:15
#5  0x00007ffff7b9128f in clickhouse::CodedOutputStream::Flush (this=0x7fffffffe1a8) at /home/idc/clickhouse-cpp/clickhouse/base/coded.cpp:82
#6  0x00007ffff7b995f7 in clickhouse::Client::Impl::SendHello (this=0x7fffffffe050) at /home/idc/clickhouse-cpp/clickhouse/client.cpp:496
#7  0x00007ffff7b98122 in clickhouse::Client::Impl::Handshake (this=0x7fffffffe050) at /home/idc/clickhouse-cpp/clickhouse/client.cpp:205
#8  0x00007ffff7b97ed6 in clickhouse::Client::Impl::Insert (this=0x7fffffffe050, table_name=..., block=...) at /home/idc/clickhouse-cpp/clickhouse/client.cpp:179
#9  0x00007ffff7b99a5e in clickhouse::Client::Insert (this=0x613c20, table_name=..., block=...) at /home/idc/clickhouse-cpp/clickhouse/client.cpp:562
#10 0x00007ffff7b9a0e9 in clickhouse::clickhouse_insert (db=0x613c20, table_name=0x400abf "test.client", block=0x613cc0) at /home/idc/clickhouse-cpp/clickhouse/client.cpp:617
#11 0x00000000004009e8 in main () at test_main.c:12>
```

**Comment by jarwin123** [comment]
@artpaul ，can you help me？thank you

**Comment by artpaul** [comment]
Yes, try to fix it today.

**Comment by artpaul** [comment]
So I added the code witch throw an exception in case if a connection to given address can't be established.

But you still may receive the SIGPIPE if the connection will be lost at some point of program execution. To avoid hang up of the program you should ignore SIGPIPE. In case of unix do the following: 
```(cpp) 
#include <signal.h>
...
int main(...) {
    signal(SIGPIPE, SIG_IGN);
}
```
