### ISSUE TITLE
segfault on inserting data into Array(Array(Array(...)))

### ISSUE THREAD

**Issue by wawaka** [artpaul/clickhouse-cpp#65]
I have encountered a problem that I can't insert into `Array(Array(Array(...)))` column.

However, inserting into `Array(Array(...))` and `Array(...)` works fine for me.

The following code tries to insert some data into multidimensional arrays. For some reason, it works only for 1- and 2-dimensional array, but segfaults for 3-dimensional.

In my case it segfaults if I uncomment the code in the provided sample.

```
Program received signal SIGSEGV, Segmentation fault.
clickhouse::ColumnArray::AppendAsColumn (this=this@entry=0x69f300, array=std::shared_ptr (empty) 0x0) at /home/vlk/projects/clickhouse-inserter/clickhouse-cpp/clickhouse/columns/array.cpp:15
15          if (!data_->Type()->IsEqual(array->Type())) {
(gdb) bt
#0  clickhouse::ColumnArray::AppendAsColumn (this=this@entry=0x69f300, array=std::shared_ptr (empty) 0x0) at /home/vlk/projects/clickhouse-inserter/clickhouse-cpp/clickhouse/columns/array.cpp:15
#1  0x0000000000453eb2 in clickhouse::ColumnArray::Append (this=0x69f300, column=...) at /home/vlk/projects/clickhouse-inserter/clickhouse-cpp/clickhouse/columns/array.cpp:41
#2  0x00000000004537fd in clickhouse::ColumnArray::AppendAsColumn (this=0x69f5d0, array=std::shared_ptr (count 4, weak 1) 0x69f910)
    at /home/vlk/projects/clickhouse-inserter/clickhouse-cpp/clickhouse/columns/array.cpp:27
#3  0x0000000000441b8c in main () at /home/vlk/projects/clickhouse-inserter/main.cpp:194
```

```cpp
#include <clickhouse/client.h>

using namespace clickhouse;

int main() {
    try {
        ClientOptions options;
        options.SetHost("localhost");
        options.SetUser("default");
        Client client(options);

        Block block;
        {
            auto a = std::make_shared<ColumnArray>(
                std::make_shared<ColumnString>()
            );
            {
                auto s = std::make_shared<ColumnString>();
                for (int i = 0; i <= 1; ++i) {
                    s->Append(std::to_string(i));
                }
                a->AppendAsColumn(s);
            }
            block.AppendColumn("a", a);
        }

        {
            auto aa = std::make_shared<ColumnArray>(
                std::make_shared<ColumnArray>(
                    std::make_shared<ColumnString>()
                )
            );
            {
                auto a = std::make_shared<ColumnArray>(
                    std::make_shared<ColumnString>()
                );
                for (int i = 0; i < 1; ++i) {
                    auto s = std::make_shared<ColumnString>();
                    for (int j = 0; j < 1; ++j) {
                        s->Append(std::to_string(i) + '.' + std::to_string(j));
                    }
                    a->AppendAsColumn(s);
                }
                aa->AppendAsColumn(a);
            }
            block.AppendColumn("aa", aa);
        }

        {
            auto aaa = std::make_shared<ColumnArray>(
                std::make_shared<ColumnArray>(
                    std::make_shared<ColumnArray>(
                        std::make_shared<ColumnString>()
                    )
                )
            );
            {
                auto aa = std::make_shared<ColumnArray>(
                    std::make_shared<ColumnArray>(
                        std::make_shared<ColumnString>()
                    )
                );
                // uncomment the code below to segfault
                // for (int i = 0; i < 1; ++i) {
                //     auto a = std::make_shared<ColumnArray>(
                //         std::make_shared<ColumnString>()
                //     );
                //     for (int j = 0; j < 1; ++j) {
                //         auto s = std::make_shared<ColumnString>();
                //         for (int k = 0; k < 1; ++k) {
                //             s->Append(std::to_string(i) + '.' + std::to_string(j) + '.' + std::to_string(k));
                //         }
                //         a->AppendAsColumn(s);
                //     }
                //     aa->AppendAsColumn(a);
                // }
                aaa->AppendAsColumn(aa);
            }
            block.AppendColumn("aaa", aaa);
        }

        client.Insert("default.test_array", block);
    } catch (const std::exception& e) {
        std::cerr << e.what() << "\n";
    }

    return 0;
}
```

**Comment by artpaul** [comment]
It should work now.
